---
engines:
  staticcheck:
    enabled: true
  # fixme:
  #   enabled: true
  # gofmt:
  #   enabled: true
  # golint:
  #   enabled: true
  #   exclude_paths:
  #     - "**_test.go"
  # govet:
  #   enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
  - "vendor/"
  - ".wercker/"
